### ISSUE TITLE
Issue with Visa scraper

### ISSUE THREAD

**Issue by asamarom** [eshaham/israeli-ynab-updater#172]
I'm getting the following:
`Run task scrapers
scraping Visa Cal
Visa Cal: START_SCRAPING
Visa Cal: INITIALIZING
Visa Cal: LOGGING_IN
Visa Cal: LOGIN_SUCCESS
Visa Cal: TERMINATING
Visa Cal: END_SCRAPING
success: false
error type: GENERIC
error: invalid json response body at https://cal4u.cal-online.co.il/Cal4U/CardsByAccounts reason: Unexpected end of JSON input
Error: invalid json response body at https://cal4u.cal-online.co.il/Cal4U/CardsByAccounts reason: Unexpected end of JSON input
    at exports.default (/home/pi/Documents/exp/israeli-ynab-updater/src/scrape/scrape-base.js:61:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4108) UnhandledPromiseRejectionWarning: Error: invalid json response body at https://cal4u.cal-online.co.il/Cal4U/CardsByAccounts reason: Unexpected end of JSON input
    at exports.default (/home/pi/Documents/exp/israeli-ynab-updater/src/scrape/scrape-base.js:61:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by eshaham** [comment]
@asamarom there is an issue with the Visa Cal scraper, we may need to rewrite it
https://github.com/eshaham/israeli-bank-scrapers/issues/602

**Comment by asamarom** [comment]
@eshaham, now that there is a new Visa scraper, is there an update I need to do in order to have it on my end?
