### ISSUE TITLE
Visa Cal scraper fails

### ISSUE THREAD

**Issue by ptc-bsorek** [eshaham/israeli-ynab-updater#44]
I tried running the visa cal scraper (site: https://www.cal-online.co.il/) and I get the following error:

scraping Visa Cal
Visa Cal: START_SCRAPING
Visa Cal: INITIALIZING
Visa Cal: LOGGING_IN
Visa Cal: TERMINATING
Visa Cal: END_SCRAPING
success: false
error type: generic
error: invalid json response body at https://restservices.cal-online.co.il/Cal4U/CalAuthenticator reason: Unexpected token < in JSON at position 0
Error: invalid json response body at https://restservices.cal-online.co.il/Cal4U/CalAuthenticator reason: Unexpected token < in JSON at position 0
    at /Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:62:11
    at Generator.next (<anonymous>)
    at step (/Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:47:191)
    at /Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:47:361
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by eshaham** [comment]
@ptc-bsorek seems to be working for me.
perhaps you could run it in debug mode and see what's happening in the browser?
```
npm run start:debug
```

**Comment by bsorek** [comment]
it doesn't open up the browser, it seems like it's attempting to do a REST call.

**Comment by ptc-bsorek** [comment]
any idea on what can be wrong here?

**Comment by eshaham** [comment]
@bsorek right, slipped my mind it was a different kind of scraper
well, since it is working fine for me, you will probably need to try debugging yourself.
you can do it by running `babel-node --inspect src`

**Comment by Hakosem** [comment]
@ptc-bsorek I have an issue with Cal too. it successfully log in but fails to scrape
