### ISSUE TITLE
Visa CAL issue

### ISSUE THREAD

**Issue by dudutwizer** [eshaham/israeli-ynab-updater#71]
scraping Visa Cal
Visa Cal: START_SCRAPING
Visa Cal: INITIALIZING
Visa Cal: LOGGING_IN
Visa Cal: LOGIN_SUCCESS
Visa Cal: TERMINATING
Visa Cal: END_SCRAPING
success: false
error type: GENERIC
error: unknown transaction type 60
Error: unknown transaction type 60
    at exports.default (/Users/dudut/Dudu/local code/israeli-ynab-updater/src/scrape/scrape-base.js:61:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at exports.default (/Users/dudut/Dudu/local code/israeli-ynab-updater/src/scrape/scrape-task.js:82:33)
    at exports.default (/Users/dudut/Dudu/local code/israeli-ynab-updater/src/scrape/scraping-main-menu.js:30:7)
(node:27638) UnhandledPromiseRejectionWarning: Error: unknown transaction type 60
    at exports.default (/Users/dudut/Dudu/local code/israeli-ynab-updater/src/scrape/scrape-base.js:61:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at exports.default (/Users/dudut/Dudu/local code/israeli-ynab-updater/src/scrape/scrape-task.js:82:33)
    at exports.default (/Users/dudut/Dudu/local code/israeli-ynab-updater/src/scrape/scraping-main-menu.js:30:7)
(node:27638) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27638) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by eshaham** [comment]
@dudutwizer please re-open in https://github.com/eshaham/israeli-bank-scrapers, unrelated to this repo.
since this is a transaction type we don't handle, would be great if you help us debug and understand the type when you open the issue.
